# 网址监控系统 - 包含Nginx的完整部署配置
# 支持自定义端口，避免端口冲突

services:
  # 后端服务
  backend:
    image: leenbj68719929/website-monitor-backend:latest
    container_name: website-monitor-backend
    restart: unless-stopped
    
    environment:
      # 数据库配置
      - DATABASE_URL=mysql://${DB_USER}:${DB_PASSWORD}@mysql:3306/${DB_NAME}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      
      # 应用安全配置
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      
      # 邮件配置
      - MAIL_SERVER=${MAIL_SERVER}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USE_TLS=${MAIL_USE_TLS}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      
      # 运行环境配置
      - FLASK_ENV=production
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - TZ=${TZ:-Asia/Shanghai}
      - PYTHONUNBUFFERED=1
    
    ports:
      - "${BACKEND_PORT:-5000}:5000"
    
    volumes:
      - ./data/backend:/app/database
      - ./logs/backend:/app/backend/logs
      - ./uploads:/app/backend/uploads
      - ./downloads:/app/backend/downloads
      - ./user_files:/app/backend/user_files
    
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    
    networks:
      - monitor_network
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
  
  # Nginx反向代理和静态文件服务
  nginx:
    image: nginx:alpine
    container_name: website-monitor-nginx
    restart: unless-stopped
    
    ports:
      - "${NGINX_HTTP_PORT:-85}:80"
      - "${NGINX_HTTPS_PORT:-448}:443"
    
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./frontend/dist:/var/www/html
      - ./ssl:/etc/ssl/certs
      - ./logs/nginx:/var/log/nginx
    
    depends_on:
      - backend
    
    networks:
      - monitor_network
      - frontend_network
    
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.25'
  
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: website-monitor-mysql
    restart: unless-stopped
    
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - TZ=${TZ:-Asia/Shanghai}
    
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/conf:/etc/mysql/conf.d
      - ./backups:/backups
    
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --max_connections=200
      --innodb_buffer_pool_size=256M
    
    networks:
      - monitor_network
    
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USER}", "-p${DB_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
  
  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: website-monitor-redis
    restart: unless-stopped
    
    command: >
      redis-server 
      --requirepass ${REDIS_PASSWORD}
      --appendonly yes
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
    
    ports:
      - "${REDIS_PORT:-6379}:6379"
    
    volumes:
      - ./data/redis:/data
      - ./redis/conf:/usr/local/etc/redis
    
    networks:
      - monitor_network
    
    healthcheck:
      test: ["CMD", "redis-cli", "auth", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'

  # PhpMyAdmin数据库管理工具
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: website-monitor-phpmyadmin
    restart: unless-stopped
    
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - UPLOAD_LIMIT=100M
    
    ports:
      - "${PHPMYADMIN_PORT:-8080}:80"
    
    depends_on:
      mysql:
        condition: service_healthy
    
    networks:
      - monitor_network
    
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'

  # Redis管理工具
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: website-monitor-redis-commander
    restart: unless-stopped
    
    environment:
      - REDIS_HOSTS=local:redis:6379:0:${REDIS_PASSWORD}
      - HTTP_USER=${REDIS_ADMIN_USER:-admin}
      - HTTP_PASSWORD=${REDIS_ADMIN_PASSWORD:-admin123}
    
    ports:
      - "${REDIS_COMMANDER_PORT:-8081}:8081"
    
    depends_on:
      redis:
        condition: service_healthy
    
    networks:
      - monitor_network
    
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.25'

# 网络配置
networks:
  monitor_network:
    driver: bridge
    internal: true
  frontend_network:
    driver: bridge