name: Backend Docker Build and Push to Docker Hub

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'backend/**'
      - 'requirements.txt'
      - 'Dockerfile'
      - 'start.sh'
      - '.github/workflows/backend-docker.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'requirements.txt'
      - 'Dockerfile'

env:
  DOCKER_HUB_REPO: website-monitor-backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_HUB_REPO }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}
          type=raw,value={{date 'YYYYMMDD-HHmmss'}}
          
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64,linux/arm64
        
    - name: Update Docker Hub description
      if: github.ref == 'refs/heads/main'
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_HUB_REPO }}
        short-description: "网址监控系统后端服务 - Website Monitor Backend Service"
        readme-filepath: ./README.md
        
    - name: Notify deployment webhook (optional)
      if: github.ref == 'refs/heads/main'
      run: |
        if [ ! -z "${{ secrets.DEPLOY_WEBHOOK }}" ]; then
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"image":"${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_HUB_REPO }}:latest","tag":"latest","commit":"${{ github.sha }}"}' \
            ${{ secrets.DEPLOY_WEBHOOK }}
        fi